spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: amogelang
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: postgres
    password: amogelang
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: DD314812A48252B94HJDY44F4FD14D4D7D1D4DJDHGGHG55FTFSR5FWHDUE3YUDFBEFCUIEGCYU
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088